name: Deploy Supabase

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/migrations/**'
      - 'supabase/functions/**'
      - 'supabase/config.toml'
  # Permite executar manualmente através da interface do GitHub
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Download Supabase CLI
        run: |
          curl -fsSL https://github.com/supabase/cli/releases/download/v1.142.2/supabase_1.142.2_linux_amd64.deb -o supabase.deb
          sudo dpkg -i supabase.deb
          supabase --version
        
      - name: Login no Supabase
        run: supabase login --token ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        
      - name: Vincular ao projeto Supabase
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
        
      - name: Deploy das migrações do banco de dados
        run: supabase db push
        
      - name: Deploy das Edge Functions
        run: supabase functions deploy
        
      - name: Verificar status
        run: supabase status
        
      - name: Notificar conclusão
        run: echo "✅ Deploy concluído com sucesso!" 