name: Deploy Supabase

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/migrations/**'
      - 'supabase/functions/**'
      - 'supabase/config.toml'
  # Permite executar manualmente através da interface do GitHub
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: false
      
      - name: Criar package.json e yarn.lock para o CI
        run: |
          echo '{
            "name": "supabase-dkseventos",
            "version": "1.0.0",
            "private": true,
            "dependencies": {
              "@supabase/supabase-js": "^2.39.0"
            }
          }' > package.json
          touch yarn.lock
          
      - name: Instalar Yarn
        run: npm install -g yarn
          
      - name: Instalar dependências
        run: yarn install --no-lockfile
        
      - name: Instalar Supabase CLI
        run: yarn global add @supabase/cli
        
      - name: Login no Supabase
        run: yarn supabase login --token ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        
      - name: Vincular ao projeto Supabase
        run: yarn supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
        
      - name: Deploy das migrações do banco de dados
        run: yarn supabase db push
        
      - name: Deploy das Edge Functions
        run: yarn supabase functions deploy
        
      - name: Verificar status
        run: yarn supabase status
        
      - name: Notificar conclusão
        run: echo "✅ Deploy concluído com sucesso!" 