name: Deploy Supabase

on:
  push:
    branches: [main]
    paths:
      - 'supabase/migrations/**'
      - 'supabase/functions/**'
      - 'supabase/config.toml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Vincular ao projeto Supabase
        run: supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: Aplicar migrações do banco de dados
        run: supabase db push --db-url $SUPABASE_DB_URL

      - name: Deploy das Edge Functions
        run: supabase functions deploy --project-ref $SUPABASE_PROJECT_ID

      - name: Verificar status
        run: supabase status

      - name: Notificar conclusão
        run: echo "✅ Deploy concluído com sucesso!"
